# Generated by Django 2.1.7 on 2019-07-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
